apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: $(namespace)
  name: istio-ingressgateway-certs
spec:
  secretName: istio-ingressgateway-certs
  dnsNames:
  - $(domain)
  commonName: $(domain)
  isCA: true
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
