apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
spec:
  secretName: istio-ingressgateway-certs
  dnsNames:
  - $(domain)
  commonName: $(domain)
  isCA: true
  issuerRef:
    kind: Issuer
    name: acme
