apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: acme
spec:
  acme:
    email: $(email)
    server: $(acmeUrl)
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - selector: {}
      http01:
       ingress:
         class: istio

