apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
- certificate.yaml
- issuer.yaml


configMapGenerator:
- name: istio-production-config
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: domain
  objref:
    kind: ConfigMap
    name: ingressgateway-acme-cert-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.domain
- name: email
  objref:
    kind: ConfigMap
    name: ingressgateway-acme-cert-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.email

configurations:
- params.yaml

