apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- issuer.yaml


configMapGenerator:
- name: istio-production-config
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

